// const age = 50;
const age: number = 50;
// const username = 'Max';
const username: string = 'Max';
// const toggle = true;
const toggle: boolean = true;
// const empty = null;
const empty: null = null;
// const callback = (a) => { return 100 + a };
const callback: (a: number) => number = (a) => { return 100 + a };